[package]
name = "test_plugin"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
libc = "0.2"
xdg = "2.5.1"
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]  # This tells Rust to build a dynamic library

